name: restaurant_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.3.8"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.2
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.3
  connectivity_plus: ^2.3.9
  sqflite: ^2.2.0+3
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  flutter_local_notifications: ^12.0.3
  rxdart: ^0.27.5
  android_alarm_manager_plus: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.0.15
  build_runner: ^2.1.6
  # sqflite_common_ffi: ^2.1.1+1
  # test: ^1.22.0
  # flutter_lints: ^2.0.0
  # build_runner: ^2.3.2
  # mockito: ^5.3.2
  # sqflite_common_ffi: ^2.1.1+1
  # test_api: ^0.4.16

flutter:
  uses-material-design: true

  assets:
    - assets/images/no-order.jpg
    - assets/images/no-favorite.jpg
    - assets/json/local_restaurant.json
